- main.go
Я попытался на быструю руку подправить внешний вид алертов.
Основная проблема была в том, что метки выводились каждый раз в разном порядке.
Вторая проблема была в том, что в web.telegram.org значения меток отформатированные через `<pre>` выводились каждое на отдельной строке - заменил на `<code>` в надежде что это поможет, но не тестировал.
Изменения лучше смотреть по отдельным коммитам, будет нагляднее.
> more readable alerts, resolve #3495

- README.md
- main.go
- template.tmpl
Add support for templating messages.
Now is possible, customizing final message with simple template: golang template language.
Use flag -t for trigger template behavior or sprintf behavior.
Andrea
> Add template

- Dockerfile
- main.go
With these changes I managed to build prometheus_bot image using following [golang-builder](https://github.com/CenturyLinkLabs/golang-builder):
```
sudo docker run --rm \
-v "$(pwd):/src" \
-v /var/run/docker.sock:/var/run/docker.sock \
centurylink/golang-builder rutsky/prometheus_bot:0.0.4
```
where last part (rutsky/prometheus_bot:0.0.4) is image name to use for storing in local Docker instance.
I pushed this image to Docker Hub here: https://hub.docker.com/r/rutsky/prometheus_bot/, and use it with `docker pull rutsky/prometheus_bot:0.0.4`.
This is not best setup that might be (best --- is autobuilding from tag on Github and publishing to Docker Hub), but it worked for me.
Related to #10.
> Add Dockerfile for building with golang-builder

- main.go
- t/curl.t
- Fix https://github.com/inCaller/prometheus_bot/issues/13 (Flood by "Error sending message, checkout logs" messages)
- Fix https://github.com/inCaller/prometheus_bot/issues/14 (Template works only from current directory)
- Minor refactoring of template logic to avoid code repetition
FYI: I used `html/template` instead of `txt/template` for proper escaping, but it not fully solve the problem. To avoid a `503 Bad Request` from Telegram server you should follow this requirements to the HTML code: https://core.telegram.org/bots/api#html-style
> Fix custom templates for messages

- main.go
This field was empty (alertmanager versions > 0.13)
Discussion on prometheus  google groups https://groups.google.com/forum/#!topic/prometheus-users/VXC_6uvkHSg
> Fix endsAt field

- main.go
On any message in a channel (not group or supergroup) bot failed with followed message:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd0 pc=0x156d788]
goroutine 26 [running]:
main.telegramBot(0xc4201ce180)
/Users/modinintsev/go/src/github.com/PinGwynn/prometheus_bot/main.go:328 +0x178
created by main.main
/Users/modinintsev/go/src/github.com/PinGwynn/prometheus_bot/main.go:420 +0x36b
```
Fixed by checking that "update.Message" is nil. Also added "bot.Debug" if option -d is passed
> Fixed panics on any message in channel and extending debug output

- Dockerfile
* current alpine version works fine
* user should not be root
* tini helps to prevent zombies
> secure default setup

- Dockerfile
1) `apk update` is unnecessary when you use `apk add --no-cache`.
2) I assume (have successfully built this new Dockerfile) bumping go and alpine version doesn't do any harm.
> Dockerfile Improvements

- README.md
- main.go
Add `send_only: false` config to use bot only to send messages and stop listening for updates.  
It's useful for example if you want to use one bot in multiple projects, without `send_only: true` you cann't do it because telegram throws error because multiple instances listening for the bot updates
> Add send_only config

- main.go
See https://prometheus.io/docs/alerting/latest/notifications/#alert .
This field is required to use templates like this
{{ range .Alerts }}
{{ if eq .Status "firing"}}🔥<b>{{ .Status | str_UpperCase }}</b>🔥{{ end }}
{{ end }}
> Add missing 'Status' to Alert struct.

- main.go
Error on debug mode:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x89dae0]
goroutine 1 [running]:
main.main()
/prometheus_bot/main.go:418 +0x260
```
Moved debug definition after bot initialization.
> Fixed error on debug mode

- Dockerfile
[Bump golang:1.22.3-alpine](https://github.com/inCaller/prometheus_bot/commit/dcfcd9d5aa9e3df2f802efe5a2ca918596d36879)
[Bump alpine 3.19](https://github.com/inCaller/prometheus_bot/commit/ac6a5168cf129b884484c9ac9087059268482bd6)
I've upgraded and tested on my environment and all is good.
> Bump dependencies

- Dockerfile
Consolidates the `COPY` directives for `go.mod` and `go.sum` into a single line for simplicity.
> Consolidate copy directives for go.mod and go.sum in dockerfile

- main.go
This PR resolves a warning related to overwriting the `j1` variable before it is first used by initializing it with the `initial` argument in the `str_Format_Scale` and `str_Format_Byte` functions.
> Resolve warning by initializing j1 with initial argument

- main.go
This PR simplifies the loop logic in the `SanitizeMsg` function by replacing the `switch` with `if-else` checks and removing the unnecessary `exitParser` variable. This resolves the `ineffective break statement` warning and improves code clarity.
> Fix loop logic in SanitizeMsg to resolve ineffective break warning

- Dockerfile
When running the `docker build .` command, the following warnings are displayed due to inconsistent casing of `AS` in multi-stage builds:
```
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 9)
```
This PR resolves the warnings by standardizing the casing of the `AS` keyword to align with `FROM`, as recommended by Dockerfile best practices.
> Resolve build warning for FromAsCasing

- .github/workflows/ci.yml
This pull request replaces the manual installation of Hadolint with the Hadolint GitHub Action. Additionally, the `DL3003` rule, which was previously ignored, no longer needs to be bypassed.
> Use hadolint github action instead of manual installation

- main.go
This PR replaces `ioutil.ReadFile` with `os.ReadFile`, fixes `go vet` issues, removes unreachable code, and corrects a typo.
> Remove unreachable code and replace deprecated method

- go.mod
- go.sum
- main.go
This PR upgrades the `telegram-bot-api` package from v4 to v5. The update includes:
- Changing the import path to `v5`.
- Adjusting code for compatibility with API changes.
The bot has been tested to ensure it:
- Handles new chat members in groups.
- Responds to text messages correctly.
> Upgrade telegram-bot-api from v4.6.4 to v5.5.1

- main.go
This PR adds error handling for `router.Run`, specifically addressing cases where the port is already occupied by another program. If an error occurs, it will be logged and the program will terminate.
> Add error handling for router.Run
